Config = Config or {}

Config.RepeatTimeout = 2000
Config.CallRepeats = 10
Config.OpenPhone = 288

--Color scheme url https://coolors.co/04b543-25d366-636e72-1da1f2-575fcf-353b48-ff002f-ff8f1a-470b45-e55934-f9b9f2
Config.PhoneApplications = {
    ["phone"] = {
        app = "phone",
        color = "#04b543",
        icon = "fa fa-phone-alt",
        tooltipText = "Phone",
        tooltipPos = "top",
        job = false,
        blockedjobs = {},
        slot = 1,
        Alerts = 0,
        requiresVPN = false,
    },
    ["whatsapp"] = {
        app = "whatsapp",
        color = "#25d366",
        icon = "fab fa-whatsapp",
        tooltipText = "Whatsapp",
        tooltipPos = "top",
        style = "font-size: 2.8vh";
        job = false,
        blockedjobs = {},
        slot = 2,
        Alerts = 0,
        requiresVPN = false,
    },
    ["settings"] = {
        app = "settings",
        color = "#636e72",
        icon = "fa fa-cog",
        tooltipText = "Settings",
        tooltipPos = "top",
        style = "padding-right: .08vh; font-size: 2.3vh";
        job = false,
        blockedjobs = {},
        slot = 3,
        Alerts = 0,
        requiresVPN = false,
    },
    ["twitter"] = {
        app = "twitter",
        color = "#1da1f2",
        icon = "fab fa-twitter",
        tooltipText = "Twitter",
        tooltipPos = "top",
        job = false,
        blockedjobs = {},
        slot = 4,
        Alerts = 0,
        requiresVPN = false,
    },
    ["garage"] = {
        app = "garage",
        color = "#575fcf",
        icon = "fas fa-warehouse",
        tooltipText = "Vehicles",
        job = false,
        blockedjobs = {},
        slot = 5,
        Alerts = 0,
        requiresVPN = false,
    },
    ["mail"] = {
        app = "mail",
        color = "#D62839",
        icon = "fas fa-envelope",
        tooltipText = "Mail",
        tooltipPos = "right",
        job = false,
        blockedjobs = {},
        slot = 6,
        Alerts = 0,
        requiresVPN = false,
    },
    ["advert"] = {
        app = "advert",
        color = "#ff8f1a",
        icon = "fas fa-ad",
        tooltipText = "Ads",
        tooltipPos = "right",
        job = false,
        blockedjobs = {},
        slot = 7,
        Alerts = 0,
        requiresVPN = false,
    },
    ["bank"] = {
        app = "bank",
        color = "#9c88ff",
        icon = "fas fa-university",
        tooltipText = "Bank",
        job = false,
        blockedjobs = {},
        slot = 8,
        Alerts = 0,
        requiresVPN = false,
    },
    ["crypto"] = {
        app = "crypto",
        color = "#004682",
        icon = "fab fa-bitcoin",
        tooltipText = "Crypto",
        job = false,
        blockedjobs = {},
        slot = 9,
        Alerts = 0,
        requiresVPN = false,
    },
    ["houses"] = {
        app = "houses",
        color = "#27ae60",
        icon = "fas fa-home",
        tooltipText = "Houses",
        tooltipPos = "right",
        job = false,
        blockedjobs = {},
        slot = 10,
        Alerts = 0,
        requiresVPN = false,
    },
    ["plants"] = {
        app = "plants",
        color = "#1E852C",
        icon = "fas fa-leaf",
        tooltipText = "Plant Monitor",
        tooltipPos = "right",
        job = false,
        blockedjobs = {},
        slot = 11,
        Alerts = 0,
        requiresVPN = false,
    },
    ["loans"] = {
        app = "loans",
        color = "#E55934",
        icon = "fa-solid fa-money-check-dollar",
        tooltipText = "Loan Monitor",
        job = false,
        blockedjobs = {},
        slot = 12,
        Alerts = 0,
        requiresVPN = false,
    },
    ["notes"] = {
        app = "notes",
        color = "#e4dc95",
        icon = "far fa-sticky-note",
        tooltipText = "Notes",
        job = false,
        blockedjobs = {},
        slot = 13,
        Alerts = 0,
        requiresVPN = false,
    },
    ["taxi"] = {
        app = "taxi",
        color = "#FFC857",
        icon = "fa-solid fa-taxi",
        tooltipText = "Taxi",
        job = false,
        blockedjobs = {},
        slot = 14,
        Alerts = 0,
        requiresVPN = false,
    },
    ["deliveries"] = {
        app = "deliveries",
        color = "#5EB1BF",
        icon = "fa-solid fa-parachute-box",
        tooltipText = "Q'ber Eats",
        job = false,
        blockedjobs = {},
        slot = 15,
        Alerts = 0,
        requiresVPN = false,
    },
    ["groups"] = {
        app = "groups",
        color = "#9E0031",
        icon = "fas fa-users",
        tooltipText = "Groups",
        job = false,
        blockedjobs = {},
        slot = 16,
        Alerts = 0,
        requiresVPN = false,
    },
    ["pings"] = {
        app = "pings",
        color = "#A40E4C",
        icon = "fa-solid fa-location-dot",
        tooltipText = "Pinger",
        job = false,
        blockedjobs = {},
        slot = 17,
        Alerts = 0,
        requiresVPN = false,
    },
    ["auctions"] = {
        app = "auctions",
        color = "#DE6B48",
        icon = "fa-regular fa-gem",
        tooltipText = "Qbay Store",
        job = false,
        blockedjobs = {},
        slot = 18,
        Alerts = 0,
        requiresVPN = false,
    },
    ["printers"] = {
        app = "printers",
        color = "#636e72",
        icon = "fa-solid fa-print",
        tooltipText = "Printers",
        job = false,
        blockedjobs = {},
        slot = 19,
        Alerts = 0,
        requiresVPN = false,
    },
    ["darkweb"] = {
        app = "darkweb",
        color = "#191716",
        icon = "fas fa-user-secret",
        tooltipText = "DarkChat",
        tooltipPos = "right",
        job = "",
        blockedjobs = {
            ["police"] = true,
        },
        slot = 20,
        Alerts = 0,
        requiresVPN = true,
    },
    ["darklogs"] = {
        app = "darklogs",
        color = "#191716",
        icon = "fa-solid fa-book-skull",
        tooltipText = "DarkLog",
        tooltipPos = "right",
        job = "",
        blockedjobs = {
            ["police"] = true,
        },
        slot = 21,
        Alerts = 0,
        requiresVPN = true,
    },
    ["carboosts"] = {
        app = "carboosts",
        color = "#290628",
        icon = "fas fa-car-crash",
        tooltipText = "Carboost",
        tooltipPos = "right",
        job = false,
        blockedjobs = {
            ["police"] = true,
        },
        slot = 22,
        Alerts = 0,
        requiresVPN = true,
    },
    ["silkroad"] = {
        app = "silkroad",
        color = "#338FFF",
        icon = "fas fa-atom",
        tooltipText = "SilQRoad",
        job = false,
        blockedjobs = {
            ["police"] = true,
        },
        slot = 23,
        Alerts = 0,
        requiresVPN = true,
    },
    ["racing"] = {
        app = "racing",
        color = "#353b48",
        icon = "fas fa-flag-checkered",
        tooltipText = "Racing",
        job = false,
        blockedjobs = {
            ["police"] = true,
        },
        slot = 24,
        Alerts = 0,
        requiresVPN = true,
    },
    ["gang"] = {
        app = "gang",
        color = "#290628",
        icon = "fa-solid fa-user-ninja",
        tooltipText = "Gang",
        tooltipPos = "right",
        job = false,
        blockedjobs = {
            ["police"] = true,
        },
        slot = 25,
        Alerts = 0,
        requiresVPN = true,
    },
    --[[ ["test"] = {
        app = "test",
        color = "#FF002F",
        icon = "fa-solid fa-bomb",
        tooltipText = "TEST SECOND PAGE",
        job = false,
        blockedjobs = {
            "police"
        },
        slot = 21,
        Alerts = 0,
        requiresVPN = true,
    }, ]]
    
    --[[ ["meos"] = {
        app = "meos",
        color = "#004682",
        icon = "fas fa-ad",
        tooltipText = "MEOS",
        job = "police",
        blockedjobs = {},
        slot = 12,
        Alerts = 0,
    }, ]]
    --[[ ["lawyers"] = {
        app = "lawyers",
        color = "#353b48",
        icon = "fas fa-user-tie",
        tooltipText = "Law Office",
        tooltipPos = "right",
        job = false,
        blockedjobs = {},
        slot = 17,
        Alerts = 0,
    }, ]]
    
    --[[ ["store"] = {
        app = "store",
        color = "#27ae60",
        icon = "fas fa-cart-arrow-down",
        tooltipText = "App Store",
        tooltipPos = "right",
        style = "padding-right: .3vh; font-size: 2.2vh";
        job = false,
        blockedjobs = {},
        slot = 14,
        Alerts = 0,
    }, ]]
    --[[ ["trucker"] = {
        app = "trucker",
        color = "#cccc33",
        icon = "fas fa-truck-moving",
        tooltipText = "Dumbo",
        tooltipPos = "right",
        job = false,
        blockedjobs = {},
        slot = 17,
        Alerts = 0,
    }, ]]
}
Config.MaxSlots = 28

Config.StoreApps = {
    ["territory"] = {
        app = "territory",
        color = "#353b48",
        icon = "fas fa-globe-europe",
        tooltipText = "Territorium",
        tooltipPos = "right",
        style = "";
        job = false,
        blockedjobs = {},
        slot = 15,
        Alerts = 0,
        password = true,
        creator = "Qbus",
        title = "Territory",
    },
}